#!/usr/bin/env python3
"""Generate a RAYCAST PLAY script -- keyboard input for a machine with
nobody at its keyboard.

    python mkwalk.py S2 E6 S6 E4 > walk.txt
    dosdeploy walk.txt C:\\WORK
    dosexec "C:\\TOOLS\\RAYCAST.EXE PLAY C:\\WORK\\WALK.TXT SECS 20"

Each leg is a compass letter and a number of cells: `E6` means turn to face
east and walk six cells.  The camera holds FORWARD throughout; the heading
events pivot it on the spot and suppress movement while they do, so the
timing below only has to cover the walking.

WHY THE TIMING IS DERIVED AND NOT TYPED IN.  A script says WHEN things
happen, so every leg's duration depends on MOVESEC and TURNSEC in
raycast.pas.  Those are exactly the two constants most likely to be tuned
again -- they were changed twice while this feature was being written --
and a script with the old numbers baked in does not fail, it walks into
walls and produces a plausible-looking bad tour.  Keep them here, in one
place, next to a note saying where they came from.

The resolution limit is real and is worth knowing before writing one of
these by hand: events are applied once a FRAME, and the raycaster renders
at about ten frames a second, so nothing finer than a tenth of a second
means anything.  That is also why turning is expressed as a heading rather
than as "hold RIGHT for four tenths" -- see A_FACE in raycast.pas.
"""

import sys

# --- must match raycast.pas -------------------------------------------
MOVESEC = 1000          # Q8 units a second, procedure Steer
ONE     = 256           # Q8 units to a map cell
TURNSEC = 700           # angle units a second
QUART   = 256           # angle units in a right angle (ANGLES = 1024)
FPS     = 10            # what this actually renders at, for slack

TENTHS_PER_CELL = 10.0 * ONE / MOVESEC          # 2.56
TENTHS_PER_TURN = 10.0 * QUART / TURNSEC        # 3.66
# One frame of slack on every turn: the swing finishes on a frame boundary,
# not on the tenth the arithmetic says.
TURN_SLACK = 10.0 / FPS

HEADING = {"E": "EAST", "S": "SOUTH", "W": "WEST", "N": "NORTH"}


def build(legs):
    out = ["# generated by mkwalk.py -- times are tenths of a second",
           "# %s" % " ".join(legs)]
    t = 0.0
    # The camera starts at angle 0, which is east.  Assuming otherwise makes
    # a first leg of W a half turn charged as a quarter, and the walk then
    # starts before the camera has finished swinging round.
    facing = "E"
    out.append("0 +FWD")
    for leg in legs:
        d, n = leg[0].upper(), leg[1:]
        if d not in HEADING or not n.isdigit():
            raise SystemExit("mkwalk: bad leg %r, want a compass letter "
                             "and a cell count, e.g. E6" % leg)
        out.append("%d +%s" % (round(t), HEADING[d]))
        # Half a turn takes twice as long as a quarter, and staying put takes
        # none.  Cheap to be exact, and a script that starts walking before
        # the camera has finished turning grinds along the wall.
        order = "ESWN"
        steps = (order.index(d) - order.index(facing)) % 4
        quarters = 2 if steps == 2 else (1 if steps else 0)
        t += quarters * TENTHS_PER_TURN + (TURN_SLACK if quarters else 0)
        facing = d
        t += int(n) * TENTHS_PER_CELL
    out.append("%d -FWD" % round(t))
    out.append("%d +QUIT" % round(t + 2))
    return "\r\n".join(out) + "\r\n"


if __name__ == "__main__":
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    # CRLF, because it is read on DOS.
    sys.stdout.buffer.write(build(sys.argv[1:]).encode("ascii"))
